# Generated by Django 2.0.6 on 2019-10-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20191018_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
