# Generated by Django 2.0.6 on 2019-10-18 12:01

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20191018_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.FileField(upload_to=music.models.directory_path),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.FileField(upload_to=music.models.directory_path),
        ),
        migrations.AlterField(
            model_name='industry',
            name='image',
            field=models.FileField(upload_to=music.models.directory_path),
        ),
        migrations.AlterField(
            model_name='track',
            name='file',
            field=models.FileField(upload_to=music.models.directory_path),
        ),
    ]
